const properties = [
  {
    id: "gh_1",
    name: "Sunny Side Villa",
    address: "123 Sunshine St, Addis Ababa",
    type: "PRIVATE",
    images: [
      {
        url: "https://www.samiltonhotel.com/wp-content/uploads/2023/11/Deluxe-Room-The-Samilton-scaled.jpg",
        name: "Front View",
      },
      {
        url: "https://www.samiltonhotel.com/wp-content/uploads/2023/11/Deluxe-Room-The-Samilton-scaled.jpg",
        name: "Lobby",
      },
    ],
    about: {
      description:
        "A cozy villa with beautiful sunrise views and modern amenities.",
      review: { averageRating: 4.7, totalReviewers: 128 },
    },
    location: {
      continent: "Africa",
      country: "Ethiopia",
      city: "Addis Ababa",
      subcity: "Bole",
      nearby: "Near Bole International Airport",
    },
    facilities: ["Free Wi-Fi", "Breakfast included", "Airport Shuttle", "Pool"],
    contact: { phone: "+251911000001", email: "info@sunnyside.com" },
    rooms: [
      {
        id: "r1_1",
        name: "Sunrise Single Room",
        roomId: "SR001",
        type: "SINGLE",
        price: 50,
        description: "Cozy single room with garden view",
        images: [
          {
            url: "https://image-tc.galaxy.tf/wipng-3xx7lkpwqqa9r8m1nse1z6ivp/executive-two-king-room_standard.png?crop=77%2C0%2C1213%2C910",
            name: "Room view",
          },
        ],
        availability: true,
        square_meters: 20,
        max_occupancy: 1,
        beds: {
          single_beds: 1,
          double_beds: 0,
          queen_beds: 0,
          king_beds: 0,
          sofa_beds: 0,
          cribs: false,
        },
        living_features: {
          private_bathroom: true,
          bathtub: false,
          shower: true,
          hairdryer: true,
          minibar: true,
          tv: true,
          streaming_tv: false,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: true,
          microwave: false,
        },
        accessibility: { wheelchair_accessible: true },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: false,
          digital_keys: true,
        },
        last_updated: new Date(),
      },
      {
        id: "r1_2",
        name: "Sunset Double Room",
        roomId: "DR001",
        type: "DOUBLE",
        price: 80,
        description: "Double room with balcony view",
        images: [
          {
            url: "https://d18slle4wlf9ku.cloudfront.net/www.cinnamonhotels.com-1302818674/cms/imagepool/67d3caeed14bb.jpg",
            name: "Balcony view",
          },
        ],

        availability: true,
        square_meters: 35,
        max_occupancy: 2,
        beds: {
          single_beds: 0,
          double_beds: 1,
          queen_beds: 0,
          king_beds: 0,
          sofa_beds: 0,
          cribs: false,
        },
        living_features: {
          private_bathroom: true,
          bathtub: true,
          shower: true,
          hairdryer: true,
          minibar: true,
          tv: true,
          streaming_tv: true,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: true,
          microwave: true,
        },
        accessibility: { wheelchair_accessible: false },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: true,
          digital_keys: true,
        },
        last_updated: new Date(),
      },
      {
        id: "r1_1",
        name: "Sunrise Single Room",
        roomId: "SR001",
        type: "SINGLE",
        price: 50,
        description: "Cozy single room with garden view",
        images: [
          {
            url: "https://image-tc.galaxy.tf/wipng-3xx7lkpwqqa9r8m1nse1z6ivp/executive-two-king-room_standard.png?crop=77%2C0%2C1213%2C910",
            name: "Room view",
          },
        ],
        availability: true,
        square_meters: 20,
        max_occupancy: 1,
        beds: {
          single_beds: 1,
          double_beds: 0,
          queen_beds: 0,
          king_beds: 0,
          sofa_beds: 0,
          cribs: false,
        },
        living_features: {
          private_bathroom: true,
          bathtub: false,
          shower: true,
          hairdryer: true,
          minibar: true,
          tv: true,
          streaming_tv: false,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: true,
          microwave: false,
        },
        accessibility: { wheelchair_accessible: true },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: false,
          digital_keys: true,
        },
        last_updated: new Date(),
      },
      {
        id: "r1_2",
        name: "Sunset Double Room",
        roomId: "DR001",
        type: "DOUBLE",
        price: 80,
        description: "Double room with balcony view",
        images: [
          {
            url: "https://d18slle4wlf9ku.cloudfront.net/www.cinnamonhotels.com-1302818674/cms/imagepool/67d3caeed14bb.jpg",
            name: "Balcony view",
          },
        ],
        availability: true,
        square_meters: 35,
        max_occupancy: 2,
        beds: {
          single_beds: 0,
          double_beds: 1,
          queen_beds: 0,
          king_beds: 0,
          sofa_beds: 0,
          cribs: false,
        },
        living_features: {
          private_bathroom: true,
          bathtub: true,
          shower: true,
          hairdryer: true,
          minibar: true,
          tv: true,
          streaming_tv: true,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: true,
          microwave: true,
        },
        accessibility: { wheelchair_accessible: false },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: true,
          digital_keys: true,
        },
        last_updated: new Date(),
      },
    ],
    createdAt: new Date(),
  },
  {
    id: "gh_3",
    name: "Best ever home in bole",
    address: "45 Greenway Ave, Addis Ababa",
    type: "SHARED",
    images: [
      {
        url: "https://api.curl.so/asset/08b02b4a-a956-43bc-a4b3-11e1b2b139ac?file=c7da56a7-447c-4db7-80f4-ddc5b1ea12b5/presidential-suite1.jpg?quality=80&width=1600",
        name: "Garden View",
      },
      {
        url: "https://api.curl.so/asset/08b02b4a-a956-43bc-a4b3-11e1b2b139ac?file=c7da56a7-447c-4db7-80f4-ddc5b1ea12b5/presidential-suite1.jpg?quality=80&width=1600",
        name: "Common Area",
      },
    ],
    about: {
      description:
        "Shared property surrounded by lush gardens. Perfect for nature lovers.",
      review: { averageRating: 4.2, totalReviewers: 76 },
    },
    location: {
      continent: "Africa",
      country: "Ethiopia",
      city: "Addis Ababa",
      subcity: "Kirkos",
      nearby: "Near Meskel Square",
    },
    facilities: [
      "Free Wi-Fi",
      "Breakfast included",
      "Garden view",
      "Laundry service",
    ],
    contact: { phone: "+251911000002", email: "contact@greengarden.com" },
    rooms: [
      {
        id: "r2_1",
        name: "Shared Twin Room",
        roomId: "TR001",
        type: "TWIN",
        price: 30,
        description: "Shared twin room with garden view",
        images: [
          { url: "https://example.com/images/room2a.jpg", name: "Twin room" },
        ],
        availability: true,
        square_meters: 25,
        max_occupancy: 2,
        beds: {
          single_beds: 2,
          double_beds: 0,
          queen_beds: 0,
          king_beds: 0,
          sofa_beds: 0,
          cribs: false,
        },
        living_features: {
          private_bathroom: false,
          bathtub: false,
          shower: true,
          hairdryer: false,
          minibar: false,
          tv: true,
          streaming_tv: false,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: false,
          refrigerator: false,
          microwave: false,
        },
        accessibility: { wheelchair_accessible: false },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: false,
          digital_keys: false,
        },
        last_updated: new Date(),
      },
      {
        id: "r2_2",
        name: "Shared Family Room",
        roomId: "FR001",
        type: "FAMILY",
        price: 60,
        description: "Spacious room for 4 with garden access",
        images: [
          { url: "https://example.com/images/room2b.jpg", name: "Family room" },
        ],
        availability: true,
        square_meters: 45,
        max_occupancy: 4,
        beds: {
          single_beds: 2,
          double_beds: 1,
          queen_beds: 0,
          king_beds: 0,
          sofa_beds: 0,
          cribs: true,
        },
        living_features: {
          private_bathroom: true,
          bathtub: true,
          shower: true,
          hairdryer: true,
          minibar: false,
          tv: true,
          streaming_tv: true,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: true,
          microwave: true,
        },
        accessibility: { wheelchair_accessible: true },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: true,
          digital_keys: true,
        },
        last_updated: new Date(),
      },
    ],
    createdAt: new Date(),
  },
  {
    id: "gh_2",
    name: "Green Garden Property",
    address: "45 Greenway Ave, Addis Ababa",
    type: "SHARED",
    images: [
      {
        url: "https://api.curl.so/asset/08b02b4a-a956-43bc-a4b3-11e1b2b139ac?file=c7da56a7-447c-4db7-80f4-ddc5b1ea12b5/presidential-suite1.jpg?quality=80&width=1600",
        name: "Garden View",
      },
      {
        url: "https://api.curl.so/asset/08b02b4a-a956-43bc-a4b3-11e1b2b139ac?file=c7da56a7-447c-4db7-80f4-ddc5b1ea12b5/presidential-suite1.jpg?quality=80&width=1600",
        name: "Common Area",
      },
    ],
    about: {
      description:
        "Shared property surrounded by lush gardens. Perfect for nature lovers.",
      review: { averageRating: 4.2, totalReviewers: 76 },
    },
    location: {
      continent: "Africa",
      country: "Ethiopia",
      city: "Addis Ababa",
      subcity: "Kirkos",
      nearby: "Near Meskel Square",
    },
    facilities: [
      "Free Wi-Fi",
      "Breakfast included",
      "Garden view",
      "Laundry service",
    ],
    contact: { phone: "+251911000002", email: "contact@greengarden.com" },
    rooms: [
      {
        id: "r2_1",
        name: "Shared Twin Room",
        roomId: "TR001",
        type: "TWIN",
        price: 30,
        description: "Shared twin room with garden view",
        images: [
          { url: "https://example.com/images/room2a.jpg", name: "Twin room" },
        ],
        availability: true,
        square_meters: 25,
        max_occupancy: 2,
        beds: {
          single_beds: 2,
          double_beds: 0,
          queen_beds: 0,
          king_beds: 0,
          sofa_beds: 0,
          cribs: false,
        },
        living_features: {
          private_bathroom: false,
          bathtub: false,
          shower: true,
          hairdryer: false,
          minibar: false,
          tv: true,
          streaming_tv: false,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: false,
          refrigerator: false,
          microwave: false,
        },
        accessibility: { wheelchair_accessible: false },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: false,
          digital_keys: false,
        },
        last_updated: new Date(),
      },
      {
        id: "r2_2",
        name: "Shared Family Room",
        roomId: "FR001",
        type: "FAMILY",
        price: 60,
        description: "Spacious room for 4 with garden access",
        images: [
          { url: "https://example.com/images/room2b.jpg", name: "Family room" },
        ],
        availability: true,
        square_meters: 45,
        max_occupancy: 4,
        beds: {
          single_beds: 2,
          double_beds: 1,
          queen_beds: 0,
          king_beds: 0,
          sofa_beds: 0,
          cribs: true,
        },
        living_features: {
          private_bathroom: true,
          bathtub: true,
          shower: true,
          hairdryer: true,
          minibar: false,
          tv: true,
          streaming_tv: true,
          wifi_available: true,
        },
        kitchen_features: {
          coffee_maker: true,
          refrigerator: true,
          microwave: true,
        },
        accessibility: { wheelchair_accessible: true },
        hygiene_features: {
          sanitizer: true,
          hygiene_kits: true,
          digital_keys: true,
        },
        last_updated: new Date(),
      },
    ],
    createdAt: new Date(),
  },
];

export default properties;
